framework:
    secret: secret
    annotations:
        enabled: false

psi_description:
    enhancers:
        - "test"

twig:
    paths:
        - %kernel.root_dir%/views

services:
    test_enhancer:
        class: "Psi\\Bundle\\Description\\Example\\src\\TestEnhancer"
        tags:
            - { name: "psi_description.enhancer", alias: "test" }

    test_extension:
        class: "Psi\\Bundle\\Description\\Example\\src\\TestExtension"
        tags: 
            - { name: "psi_description.schema_extension", alias: "test" }
